language: ruby
rvm:
 - 2.6.0

before_install: 
- cd pokesystem
- nvm install node
- npm uninstall node-sass-middleware --save && npm install node-sass-middleware --save

install:
- bundle install
- yarn install

before_script:
- rake db:create
- rake db:schema:load
- rake db:seed

script:
- rails server -d
