version: '3'
services:
  db:
    image: postgres
    ports:
      - "5400:5432"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
        - ./pokesystem:/pokesystem
    ports:
      - "3000:3000"
    depends_on:
      - db